apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl-tester
    tier: client
  name: connectivity-test-pod
  namespace: test-1
spec:
  containers:
  - image: alpine/curl
    name: curl-tester
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    volumeMounts:
    - mountPath: /var/log
      name: webserver-log
    command:
    - /bin/sh
    - -c
    - |
      while true; do
        echo "Trying to connect to web-service" >> /var/log/webserver.log
        if curl -s web-service; then
          echo "$(date): Successfully connected to web-service" >> /var/log/webserver.log
        else
          echo "$(date): Failed to connect to web-service" >> /var/log/webserver.log
        fi
        sleep 5
      done
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: webserver-log
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver
    tier: frontend
  name: webserver-pod
  namespace: test-1
spec:
  containers:
  - image: nginx:latest
    name: webserver-container
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always