apiVersion: v1
kind: Pod
metadata:
  name: semi-secure-pod
spec:
  containers:
  - name: semi-secure-container
    image: redis
    ports:
    - containerPort: 6379
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_HOST
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_PASSWORD
    resources: # Add resource limits here
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"