apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace-access-netpol
  namespace: test-2
spec:
  podSelector:
    matchLabels:
      run: beep-beep-pod
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: test-pod