apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod-1
spec:
  # Run as root user
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
  - name: insecure-container
    image: nginx
    ports:
    - containerPort: 80
    # Allow privileged mode
    securityContext:
      allowPrivilegeEscalation: true
    # Mount sensitive host paths
    volumeMounts:
    - name: host-volume
      mountPath: /host
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
  volumes:
  - name: host-volume
    hostPath:
      path: /