apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod-2
spec:
  containers:
  - name: insecure-container
    image: redis:latest
    ports:
    - containerPort: 6379
    # Run as root user
    securityContext:
      runAsUser: 0
    # Allow privileged mode
    securityContext:
      privileged: true
    # Allow all capabilities
    securityContext:
      capabilities:
        add: ["ALL"]
    # Mount sensitive host paths
    volumeMounts:
    - name: host-volume
      mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /