apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
      - name: insecure-container
        image: nginx:latest
        ports:
        - containerPort: 8080
        # Run as root user
        securityContext:
          runAsUser: 0
          privileged: true
          add: ["ALL"]
        # Mount sensitive host paths
        volumeMounts:
        - name: host-volume
          mountPath: /host
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      volumes:
      - name: host-volume
        hostPath:
          path: /