apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
      - name: insecure-container
        image: insecure-image:latest
        ports:
        - containerPort: 8080
        # Run as root user
        securityContext:
          runAsUser: 0
        # Allow privileged mode
        securityContext:
          privileged: true
        # Allow all capabilities
        securityContext:
          capabilities:
            add: ["ALL"]
        # Mount sensitive host paths
        volumeMounts:
        - name: host-volume
          mountPath: /host
      volumes:
      - name: host-volume
        hostPath:
          path: /