apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enable-egress-web-service
  namespace: test-1
spec:
 podSelector:
   matchLabels:
      tier: client
 policyTypes:
  - Egress
 egress:
  - to:
    - podSelector:
        matchLabels:
          tier: frontend
    ports:
    - protocol: TCP
      port: 80
  - to:
    - podSelector:
        matchLabels:
          tier: cluster-frontend
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: test-2
    ports:
    - protocol: TCP
      port: 80
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53