apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enable-ingress-web-service
  namespace: test-2
spec:
 podSelector:
   matchLabels:
      tier: cluster-frontend
 policyTypes:
  - Ingress
  - Egress
 ingress:
 - from:
   - podSelector:
        matchLabels:
          tier: client
   - namespaceSelector: {}
   ports:
    - protocol: TCP
      port: 80
 egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enable-egress-web-service
  namespace: test-2
spec:
 podSelector:
   matchLabels:
      tier: client
 policyTypes:
  - Egress
 egress:
  - to:
    - podSelector:
        matchLabels:
          tier: cluster-frontend
    ports:
    - protocol: TCP
      port: 80
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53