apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  containers:
  - name: insecure-container
    image: insecure-image:latest
    ports:
    - containerPort: 8080
    # Run as root user
    securityContext:
      runAsUser: 0
    # Allow privileged mode
    securityContext:
      privileged: true
    # Allow all capabilities
    securityContext:
      capabilities:
        add: ["ALL"]
    # Mount sensitive host paths
    volumeMounts:
    - name: host-volume
      mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /