apiVersion: v1
kind: Service
metadata:
  name: web-service-2
  namespace: test-2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    tier: cluster-frontend
  type: ClusterIP