apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-sa
  namespace: imagepolicywebhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook-role
  namespace: imagepolicywebhook
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  resourceNames:
  - webhook-config-allow
  - webhook-config-disallow
  - webhook-config-exempt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-rolebinding
  namespace: imagepolicywebhook
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webhook-role
subjects: 
- kind: ServiceAccount
  name: webhook-sa
  namespace: imagepolicywebhook