apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      # Run as root user
      securityContext:
        runAsUser: 0
      containers:
      - name: insecure-container
        image: mysql:latest
        ports:
        - containerPort: 3306
        # Allow privileged mode
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
